import { APP_URL } from "@/lib/utils";
import { CREDIT_PACKAGE_LIST } from "@/lib/packages";
import { FAQS } from "@/lib/marketing/faq-data";

const ORGANIZATION_ID = `${APP_URL}/#organization`;
const WEBSITE_ID = `${APP_URL}/#website`;
const SOFTWARE_APP_ID = `${APP_URL}/#software`;

/**
 * Brand disambiguation. GSC shows singular-brand queries ("shot studio",
 * "shotstudio") converting and plural queries ("shots studio(s)") sitting at
 * position 45-81 — those belong to Shots Studios, an unrelated media company.
 * We claim only the singular spellings; we never claim theirs.
 */
const BRAND_ALTERNATE_NAMES = ["Shot Studio", "ShotStudio.dev"];
const SAME_AS = ["https://x.com/KazakisThanos"];

export function organizationSchema() {
  return {
    "@type": "Organization",
    "@id": ORGANIZATION_ID,
    name: "ShotStudio",
    alternateName: BRAND_ALTERNATE_NAMES,
    url: APP_URL,
    logo: {
      "@type": "ImageObject",
      url: `${APP_URL}/icon.png`,
    },
    email: "kazakis.th@gmail.com",
    sameAs: SAME_AS,
    description:
      "ShotStudio turns three raw mobile screenshots into a polished three-shot App Store set in under a minute. One-time pay, never stored.",
  };
}

export function websiteSchema() {
  return {
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    url: APP_URL,
    name: "ShotStudio",
    alternateName: BRAND_ALTERNATE_NAMES,
    publisher: { "@id": ORGANIZATION_ID },
    inLanguage: "en-US",
  };
}

function formatUsd(priceCents: number): string {
  return (priceCents / 100).toFixed(2);
}

/** One Offer per credit pack — real, published, one-time prices. */
function creditPackOffers() {
  return CREDIT_PACKAGE_LIST.map((pack) => ({
    "@type": "Offer",
    "@id": `${APP_URL}/pricing#${pack.id}`,
    name: `${pack.name} — ${pack.credits} ${pack.credits === 1 ? "set" : "sets"}`,
    description: `${pack.credits} generation ${pack.credits === 1 ? "set" : "sets"} (${pack.credits * 3} polished 1290×2796 App Store screenshots). One-time purchase, credits never expire.`,
    price: formatUsd(pack.priceCents),
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
    url: `${APP_URL}/pricing`,
    seller: { "@id": ORGANIZATION_ID },
    priceSpecification: {
      "@type": "UnitPriceSpecification",
      price: formatUsd(pack.priceCents),
      priceCurrency: "USD",
      valueAddedTaxIncluded: false,
      referenceQuantity: {
        "@type": "QuantitativeValue",
        value: pack.credits,
        unitText: "generation set",
      },
    },
    eligibleQuantity: {
      "@type": "QuantitativeValue",
      value: pack.credits,
      unitText: "generation set",
    },
  }));
}

/**
 * AggregateOffer spanning the three packs — $7 floor, $37 ceiling.
 * Used as the `offers` value of the SoftwareApplication entity so price and
 * availability are machine-readable without claiming a Product review.
 */
function creditPackAggregateOffer() {
  const cents = CREDIT_PACKAGE_LIST.map((pack) => pack.priceCents);
  return {
    "@type": "AggregateOffer",
    priceCurrency: "USD",
    lowPrice: formatUsd(Math.min(...cents)),
    highPrice: formatUsd(Math.max(...cents)),
    offerCount: CREDIT_PACKAGE_LIST.length,
    availability: "https://schema.org/InStock",
    url: `${APP_URL}/pricing`,
    seller: { "@id": ORGANIZATION_ID },
    offers: creditPackOffers(),
  };
}

/**
 * The single canonical entity for the product.
 *
 * Deliberately NOT `Product`. ShotStudio has zero published customer reviews,
 * so a Product node can never satisfy Google's `review` / `aggregateRating`
 * recommendations without fabricating them — which is a structured-data policy
 * violation. `SoftwareApplication` + `AggregateOffer` describes a web app sold
 * in one-time credit packs accurately and has no rating requirement.
 */
export function softwareApplicationSchema() {
  return {
    "@type": "SoftwareApplication",
    "@id": SOFTWARE_APP_ID,
    name: "ShotStudio",
    alternateName: BRAND_ALTERNATE_NAMES,
    applicationCategory: "DesignApplication",
    applicationSubCategory: "App Store screenshot generator",
    operatingSystem: "Web",
    browserRequirements: "Requires a modern browser with JavaScript enabled.",
    url: APP_URL,
    inLanguage: "en-US",
    isAccessibleForFree: false,
    description:
      "Turn three raw mobile screenshots into a polished three-image App Store set at 1290×2796, generated by AI. One-time credit packs, no subscription.",
    offers: creditPackAggregateOffer(),
    publisher: { "@id": ORGANIZATION_ID },
    provider: { "@id": ORGANIZATION_ID },
    audience: {
      "@type": "Audience",
      audienceType: "Indie iOS developers shipping to the App Store",
    },
    featureList: [
      "AI-generated App Store screenshots",
      "1290×2796 iPhone 6.7\" portrait output",
      "Four personality presets (Friendly, Professional, Minimal, Bold) — typography and headline voice",
      "Theme and palette derived from your uploaded screenshots (light app stays light, dark app stays dark)",
      "AI-written headline from your pitch and audience",
      "Auto-refund on failed generations",
      "Zero image persistence",
    ],
  };
}

export function faqPageSchema(faqs: { q: string; a: string }[] = FAQS) {
  return {
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.a,
      },
    })),
  };
}

export function breadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function itemListSchema({
  id,
  name,
  items,
}: {
  id: string;
  name: string;
  items: { name: string; url: string }[];
}) {
  return {
    "@type": "ItemList",
    "@id": id,
    name,
    numberOfItems: items.length,
    itemListOrder: "https://schema.org/ItemListUnordered",
    itemListElement: items.map((entry, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: entry.name,
      url: entry.url,
      item: {
        "@type": "WebPage",
        "@id": entry.url,
        url: entry.url,
        name: entry.name,
      },
    })),
  };
}

export function webPageSchema({
  url,
  name,
  description,
  primaryImage,
  about,
  mentions,
}: {
  url: string;
  name: string;
  description: string;
  primaryImage?: string;
  about?: Record<string, unknown>;
  mentions?: Record<string, unknown>[];
}) {
  return {
    "@type": "WebPage",
    "@id": url,
    url,
    name,
    description,
    inLanguage: "en-US",
    isPartOf: { "@id": WEBSITE_ID },
    publisher: { "@id": ORGANIZATION_ID },
    ...(primaryImage
      ? {
          primaryImageOfPage: {
            "@type": "ImageObject",
            url: primaryImage,
          },
        }
      : {}),
    ...(about ? { about } : {}),
    ...(mentions ? { mentions } : {}),
  };
}
