import { APP_URL } from "@/lib/utils";
import { CREDIT_PACKAGE_LIST } from "@/lib/packages";
import { FAQS } from "@/lib/marketing/faq-data";

const ORGANIZATION_ID = `${APP_URL}/#organization`;
const WEBSITE_ID = `${APP_URL}/#website`;
const SOFTWARE_APP_ID = `${APP_URL}/#software`;

export function organizationSchema() {
  return {
    "@type": "Organization",
    "@id": ORGANIZATION_ID,
    name: "ShotStudio",
    url: APP_URL,
    logo: `${APP_URL}/icon.png`,
    email: "hello@shotstudio.app",
    description:
      "ShotStudio turns three raw mobile screenshots into a polished four-shot App Store set in under a minute. One-time pay, never stored.",
  };
}

export function websiteSchema() {
  return {
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    url: APP_URL,
    name: "ShotStudio",
    publisher: { "@id": ORGANIZATION_ID },
    inLanguage: "en-US",
  };
}

export function softwareApplicationSchema() {
  const cheapest = CREDIT_PACKAGE_LIST.reduce((min, pack) =>
    pack.priceCents < min.priceCents ? pack : min,
  );
  return {
    "@type": "SoftwareApplication",
    "@id": SOFTWARE_APP_ID,
    name: "ShotStudio",
    applicationCategory: "DesignApplication",
    applicationSubCategory: "App Store screenshot generator",
    operatingSystem: "Web",
    url: APP_URL,
    description:
      "Turn three raw mobile screenshots into a polished four-image App Store set at 1290×2796, generated by AI. One-time credit packs, no subscription.",
    offers: {
      "@type": "Offer",
      price: (cheapest.priceCents / 100).toFixed(2),
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: `${APP_URL}/pricing`,
    },
    publisher: { "@id": ORGANIZATION_ID },
    featureList: [
      "AI-generated App Store screenshots",
      "1290×2796 iPhone 6.7\" portrait output",
      "Four style presets (soft bright, dark premium, clean minimal, bold playful)",
      "AI-written headline from your pitch and audience",
      "Auto-refund on failed generations",
      "Zero image persistence",
    ],
  };
}

export function faqPageSchema() {
  return {
    "@type": "FAQPage",
    mainEntity: FAQS.map((faq) => ({
      "@type": "Question",
      name: faq.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.a,
      },
    })),
  };
}

export function pricingProductSchema() {
  return {
    "@type": "Product",
    name: "ShotStudio credit pack",
    description:
      "One-time credit packs for App Store screenshot generation. Each credit produces one four-shot set at 1290×2796.",
    brand: { "@id": ORGANIZATION_ID },
    offers: CREDIT_PACKAGE_LIST.map((pack) => ({
      "@type": "Offer",
      name: `${pack.name} — ${pack.credits} ${pack.credits === 1 ? "set" : "sets"}`,
      price: (pack.priceCents / 100).toFixed(2),
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: `${APP_URL}/pricing`,
      priceSpecification: {
        "@type": "UnitPriceSpecification",
        price: (pack.priceCents / 100).toFixed(2),
        priceCurrency: "USD",
        referenceQuantity: {
          "@type": "QuantitativeValue",
          value: pack.credits,
          unitText: "generation set",
        },
      },
      eligibleQuantity: {
        "@type": "QuantitativeValue",
        value: pack.credits,
        unitText: "generation set",
      },
    })),
  };
}

export function breadcrumbSchema(
  items: { name: string; url: string }[],
) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

